baseURL = 'https://craigtracey.github.io/validated-solutions/'
languageCode = 'en-us'
title = 'Tanzu Validated Solutions'
theme = 'vmw-preview'

[security]
  [security.funcs]
    getenv = ['^HUGO_', 'PWD']